export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const GET_ARTISTS_SUCCESS = 'GET_ARTISTS_SUCCESS';
export const GET_ARTIST_SUCCESS = 'GET_ARTIST_SUCCESS';
export const GET_TOP_ALBUMS_SUCCESS = 'GET_TOP_ALBUMS_SUCCESS';
